version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54322:5432"
  redis:
    image: redis:alpine
    ports:
      - "63799:6379"
  web:
    build: .
    command: "gunicorn hillelDjango4.wsgi --bind=0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: always
    volumes:
      - .:/app
  migrations:
    build: .
    command: "python manage.py migrate"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    restart: "no"
    volumes:
      - .:/app
  celery:
    build: .
    command: "celery -A hillelDjango4 worker -l info"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: always
    volumes:
      - .:/app
  react:
    build: ../hillel-react
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ../hillel-react:/app
