# Generated by Django 5.0.7 on 2024-08-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_products_store_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
        migrations.RemoveField(
            model_name='store',
            name='quantity',
        ),
    ]
