# Generated by Django 5.0.7 on 2024-08-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('products', '0002_alter_product_category'),
        ('stores', '0003_remove_store_products_remove_store_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(related_name='stores', through='inventory.Inventory', to='products.product'),
        ),
    ]
