# Generated by Django 5.0.7 on 2024-08-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_products',
            field=models.ManyToManyField(related_name='order_products', to='orders.orderproduct'),
        ),
    ]
